pipeline:
    name: gitSimpExpvThree
    identifier: gitSimpExpvThree
    projectIdentifier: dougproject
    orgIdentifier: default
    storeType: REMOTE
    remoteType: create
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: douglasjbothwellgithub
                repoName: gitSimpExpvThree
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: docsgkedbothwellciquickstart
                          namespace: harness-delegate-ng
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: echo hello-world
                                identifier: echo_helloworld
                                spec:
                                    connectorRef: dbothwelldockerhub
                                    image: alpine/latest
                                    shell: Sh
                                    command: echo "hello world in my-feature-branch"
